[package]
name = "measure_air_dust"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.17.1"
serde = {version="1.0.200", features=["derive"]}
chrono = {version="0.4.38", features=["serde"]}

